server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:nuevospa
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret:  mySuperSecretJwtKeyThatIsAtLeast32CharactersLong2026
  expiration: 3600000
  refresh-expiration: 86400000